#![allow(clippy::pedantic)]
#![allow(clippy::unwrap_used)]

//! Build script for txtify — embeds `sidecar/` into the binary manifest.
//! Ensures reproducible builds and that `cargo` reruns when sidecar changes.

use std::path::Path;

fn main() {
    // Rerun if sidecar contents change
    println!("cargo:rerun-if-changed=sidecar/");
    println!("cargo:rerun-if-changed=sidecar/txtify_sidecar.py");
    println!("cargo:rerun-if-changed=sidecar/requirements.txt");
    println!("cargo:rerun-if-changed=build.rs");

    // Validate sidecar exists; emit env flag for `include_bytes!` usage
    let sidecar_path = Path::new("sidecar/txtify_sidecar.py");
    if sidecar_path.exists() {
        println!("cargo:rustc-env=TXTIFY_SIDECAR_PATH=sidecar/txtify_sidecar.py");
        // Optionally, embed file list count
        let count = std::fs::read_dir("sidecar").map(|d| d.count()).unwrap_or(0);
        println!("cargo:rustc-env=TXTIFY_SIDECAR_FILE_COUNT={count}");

        // Embed sidecar file contents into OUT_DIR for inclusion via include_bytes!
        if let Ok(out_dir) = std::env::var("OUT_DIR") {
            let dest = Path::new(&out_dir).join("sidecar_manifest.rs");
            let py_content = std::fs::read_to_string(sidecar_path).unwrap_or_default();
            let req_content =
                std::fs::read_to_string("sidecar/requirements.txt").unwrap_or_default();
            let generated = format!(
                "/// Embedded sidecar manifest generated by build.rs\npub const SIDECAR_PY: &str = {py:?};\npub const SIDECAR_REQUIREMENTS: &str = {req:?};\npub const SIDECAR_FILE_COUNT: usize = {count};\n",
                py = py_content,
                req = req_content,
                count = count
            );
            let _ = std::fs::write(&dest, generated);
        }
    } else {
        println!("cargo:warning=sidecar/txtify_sidecar.py not found; high-quality mode will require external sidecar");
    }

    // Embed sidecar version if available via git
    println!(
        "cargo:rustc-env=TXTIFY_BUILD_PROFILE={}",
        std::env::var("PROFILE").unwrap_or_default()
    );
}
